### ISSUE TITLE
Handling different site root structure

### ISSUE THREAD

**Issue by inspiredearth** [wpbullet/wp-cli-backups-cloud-storage#2]
Thanks for this script. 
I see it is set up for the site root structure to be exclusively in the tree structure of:
```
/var/www/site1
/var/www/site2
```
This means it can't be used when the structure is something like the following fairly typical configuration:
```
/home/user/domain.com/public
/home/user/domain2.com/public
etc.
```
Trying to run the script in this situation will result in the script wrongly determining the site roots. For example, let's say I have just one site at `/home/user/domain.com/public` and I put that in as the `SITESTORE`. It will then wrongly determine that each folder in `/home/user/domain.com/public` is a site. It makes a real mess of things.

I would be great if it were able to handle the above mentioned folder structure. It's fairly common on Nginx servers to set things up that way.

**Comment by inspiredearth** [comment]
The work-around I've implemented is to set `SITESTORE="/home/user/sites/domain.com.au" `
And then set `SITELIST='public' `
That seems to have done the trick.

**Comment by wpbullet** [comment]
Glad to hear you got it working @jonathannz :)

If you are using one instance for multiple sites please make sure the php-fpm handlers are configured per site with separate users for security reasons (you probably already are!). Too many times I've seen multiple sites on the same server get hacked because of this very common oversight.

**Comment by inspiredearth** [comment]
Thanks for the advice.
In this case, there's just the one site on the server.
